### PR TITLE
Solidworks path fix

### PR DESCRIPTION
**Pull request by trootcode**
This change is to copy the solidworks interop dlls into the repository and make the path to them relative  so that different install directories for SolidWorks don't break the build

I'm new to github so please let me know if I did this pull request right.

### CODE REVIEW

**Comment by johannesegger** [comment]
Are we allowed to redistribute the SW dlls? I know it's just the interop dlls which don't contain any real code I think, but still it's IP of SW, isn't it?

**Comment by trootcode** [comment]
These dlls are located in a folder called \api\redist so I assumed they
were meant to be redistributable by a 3rd party.  I never really thought
about it though.  I'll do a quick google search to see what I can find.

Timothy Root
Pathfinder3D - Lead Developer
phone: (888) 892-5006
e-mail: troot@pathfinder3d.com sales@pathfinder3d.com
web: www.pathfinder3d.com

**Comment by trootcode** [comment]
I don't see anything obvious on the internet so I sent a quick question to
SolidWorks.  Lets see what they say.  The code from these dlls does get
embedded in the compiled app so it would be strange if they had a problem
with including them in an open source project.  But its better to hear it
from them I guess.

Timothy Root
Pathfinder3D - Lead Developer
phone: (888) 892-5006
e-mail: troot@pathfinder3d.com sales@pathfinder3d.com
web: www.pathfinder3d.com

**Comment by bradphelan** [comment]
I'll pull it when you get an answer from solidworks. I don't want to get involved with "legal" fiddly stuff.

**Comment by bradphelan** [comment]
Can you outline the actual issue you are trying to solve with this pull request?

**Comment by trootcode** [comment]
The issue I am trying to solve is I have multiple versions of SolidWorks installed on my computer.  The dlls at C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\ are the 2015 version so the project won't compile.  I have solved this in the past using the method I propose in the pull request.  But there very well might be a better way to do it.

**Comment by trootcode** [comment]
Maybe its possible to add a PropertyGroup to the .csproj.user and use that property in the hintpath?  I haven't done that before but if it works it would be one way to solve the issue without including the interop dlls and without the need for me to change the reference paths every time I update from master.  I can research this further tomorrow (my day is ending right now) if that sounds like something you would be interested in.  Let me know.

**Comment by johannesegger** [comment]
I'm closing this because #12 also solves it.

**Pull request closed without merging**
